Repository streamnative/terraform-aws-cloud, pull requests merged in 2022-06, with the labels that each got.

#71 Configure Internal or Internet-Facing NLB
  README.md
  istio.tf
  variables.tf
Labels: doc

#70 Support AWS China
  aws_load_balancer_controller.tf
  cert_manager.tf
  csi.tf
  external_dns.tf
  external_secrets.tf
  main.tf
  modules/managed-cloud/files/aws_lb_controller.json.tpl
  modules/managed-cloud/files/bootstrap_role_iam_policy.json.tpl
  modules/managed-cloud/files/bootstrap_role_iam_policy_runtime.json.tpl
  modules/managed-cloud/files/management_role_iam_policy.json.tpl
  modules/managed-cloud/files/permission_boundary_iam_policy.json.tpl
  modules/managed-cloud/files/permission_boundary_iam_policy_runtime.json.tpl
  modules/managed-cloud/main.tf
  modules/managed-cloud/variables.tf
  modules/vpc/variables.tf
Labels: doc-info-missing

#77 Support aws partition in ARN
  csi.tf
  main.tf
  modules/managed-cloud/main.tf
Labels: no-need-doc

#79 Updates to logic in the managed-cloud submodule
  modules/managed-cloud/README.md
  modules/managed-cloud/files/permission_boundary_iam_policy.json.tpl
  modules/managed-cloud/files/permission_boundary_iam_policy_runtime.json.tpl
  modules/managed-cloud/main.tf
  modules/managed-cloud/variables.tf
Labels: type/task, doc

#74 Enable passing of custom AMI and userdata.sh for Node Groups
  README.md
  main.tf
  variables.tf
Labels: doc
